package com.example.manotien.myapplication;

import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;

/**
 * Created by manotien on 20/3/2559.
 */
public class InitialData {
    public void initial(SQLiteDatabase db){
        InitHabit(db);
        InitFamily(db);
    }

    private void InitHabit(SQLiteDatabase db){
        String []habit_name ={"Aquatic","Aquatic","Fern","Aquatic","Grass","Aquatic","Herb","Aquatic","Orchid","Bamboo","Climber","Climbing","Bamboo","Climbing","Fern","Climbing","Palm","Creeper","Creeping","Herb","Creeping","Shrub","Creeping","Undershrub","Epiphyte","Epiphytic","Fern","Epiphytic","Herb","Epiphytic","Orchid","Epiphytic","Shrub","Epiphytic","Shrubby","Tree","Epiphytic","Undershrub","Exotic","Fern","Grass","Herb","Herbaceous","Climber","Holomycotrophic","Orchid","Insectivorous","Herb","Lythophytic","Fern","Orchid","Palm","Parasite","Parasitic","Climber","Parasitic","Herb","Parasitic","Herbaceous","Climber","Parasitic","Shrub","Rheophytic","Herb","Shrub","Saprophytic","Saprophytic","Herb","Scandent","Shrub","Shrubby","Tree","Tree","Terrestrial","Fern","Terrestrial","Orchid","Tree","Fern","Trailing","Herb","Undershrub","Woody","Climber"};
        for (String name :habit_name) {
            ContentValues contentv = new ContentValues();
            contentv.put("name",name);
            db.insert("habit_table", null, contentv);
        }
    }
    private void InitFamily(SQLiteDatabase db){
        String []family_name ={"ACANTHACEAE","ACHARIACEAE","ACORACEAE","ACTINIDIACEAE","ADOXACEAE","AIZOACEAE","AKANIACEAE","ALISMATACEAE","ALSTROEMERIACEAE","ALTINGIACEAE","AMARANTHACEAE","AMARYLLIDACEAE","ANACARDIACEAE","ANCISTROCLADACEAE","ANISOPHYLLEACEAE","ANNONACEAE","APIACEAE","APOCYNACEAE","APONOGETONACEAE","AQUIFOLIACEAE","ARACEAE","ARALIACEAE","ARAUCARIACEAE","ARDIOPTERIDACEAE","ARECACEAE","ARISTOLOCHIACEAE","ASPARAGACEAE","ASPLENIACEAE","ASTERACEAE","ATHYRIACEAE","BALANOPHORACEAE","BALSAMINACEAE","BASELLACEAE","BEGONIACEAE","BERBERIDACEAE","BETULACEAE","BIGNONIACEAE","BIXACEAE","BLECHNACEAE","BONNETIACEAE","BORAGINACEAE","BRASSICACEAE","BROMELIACEAE","BURMANNIACEAE","BURSERACEAE","BUXACEAE","CABOMBACEAE","CACTACEAE","CALEMANNIACEAE","CALLITRICHACEAE","CALOPHYLLACEAE","CAMPANULACEAE","CANNABACEAE","CANNACEAE","CAPPARACEAE","CAPRIFOLIACEAE","CARDIOPTERIDACEAE","CARICACEAE","CARLEMANNIACEAE","CARYOPHYLLACEAE","CASUARINACEAE","CELASTRACEAE","CENTROLEPIDACEAE","CEPHALOTAXACEAE","CERATOPHYLLACEAE","CHLORANTHACEAE","CHRYSOBALANACEAE","CIBOTIACEAE","CLEOMACEAE","CLUSIACEAE","COLCHICACEAE","COMBRETACEAE","COMMELINACEAE","CONNARACEAE","CONVOLVULACEAE","CORNACEAE","COSTACEAE","CRASSULACEAE","CRYPTERONIACEAE","CUCURBITACEAE","CUNONIACEAE","CUPRESSACEAE","CYATHEACEAE","CYCADACEAE","CYCLANTHACEAE","CYMODOCEACEAE","CYPERACEAE","DAPHNIPHYLLACEAE","DAVALLIACEAE","DENNSTAEDTIACEAE","DIDIEREACEAE","DILLENIACEAE","DIOSCOREACEAE","DIPSACACEAE","DIPTERIDACEAE","DIPTEROCARPACEAE","DROSERACEAE","DRYOPTERIDACEAE","EBENACEAE","ELAEAGNACEAE","ELAEOCARPACEAE","ELATINACEAE","EQUISETACEAE","ERICACEAE","ERIOCAULACEAE","ERYTHROXYLACEAE","ESCALLONIACEAE","EUPHORBIACEAE","FABACEAE","FAGACEAE","FLAGELLARIACEAE","FUMARIACEAE","Fabaceae","GELSEMIACEAE","GENTIANACEAE","GERANIACEAE","GESNERIACEAE","GINKGOACEAE","GLEICHENIACEAE","GNETACEAE","GOODENIACEAE","HAEMODORACEAE","HALORAGACEAE","HAMAMELIDACEAE","HANGUANACEAE","HELICONIACEAE","HELWINGIACEAE","HERNANDIACEAE","HYDRANGEACEAE","HYDROCHARITACEAE","HYDROLEACEAE","HYMENOPHYLLACEAE","HYPERICACEAE","HYPOXIDACEAE","ICACINACEAE","IRIDACEAE","IRVINGIACEAE","ISOETACEAE","ITEACEAE","IXONANTHACEAE","JUGLANDACEAE","LAMIACEAE","LARDIZABALACEAE","LAURACEAE","LECYTHIDACEAE","LENTIBULARIACEAE","LILIACEAE","LINACEAE","LINDERNIACEAE","LINDSAEACEAE","LOGANIACEAE","LOMARIOPSIDACEAE","LORANTHACEAE","LOWIACEAE","LYCOPODIACEAE","LYGODIACEAE","LYTHRACEAE","MAGNOLIACEAE","MALPIGHIACEAE","MALVACEAE","MARANTACEAE","MARATTIACEAE","MARSILEACEAE","MARTYNIACEAE","MATONIACEAE","MELANTHIACEAE","MELASTOMATACEAE","MELIACEAE","MENISPERMACEAE","MENYANTHACEAE","MOLLUGINACEAE","MONIMIACEAE","MORACEAE","MORINGACEAE","MUSACEAE","MYRICACEAE","MYRISTICACEAE","MYRTACEAE","NELUMBONACEAE","NEPENTHACEAE","NYCTAGINACEAE","NYMPHAEACEAE","OCHNACEAE","OLACACEAE","OLEACEAE","OLEANDRACEAE","ONAGRACEAE","OPHIOGLOSSACEAE","OPILIACEAE","ORCHIDACEAE","OROBANCHACEAE","OSMUNDACEAE","OXALIDACEAE","PAEONIACEAE","PANDACEAE","PANDANACEAE","PAPAVERACEAE","PASSIFLORACEAE","PAULOWNIACEAE","PEDALIACEAE","PENTAPHRAGMATACEAE","PENTAPHYLACACEAE","PERACEAE","PHILYDRACEAE","PHRYMACEAE","PHYLLANTHACEAE","PHYTOLACCACEAE","PICRODENDRACEAE","PINACEAE","PIPERACEAE","PITTOSPORACEAE","PLAGIOGYRIACEAE","PLANTAGINACEAE","PLUMBAGINACEAE","POACEAE","PODOCARPACEAE","PODOSTEMACEAE","POLEMONIACEAE","POLYGALACEAE","POLYGONACEAE","POLYPODIACEAE","PONTEDERIACEAE","PORTULACACEAE","POTAMOGETONACEAE","PRIMULACEAE","PROTEACEAE","PSILOTACEAE","PTERIDACEAE","PUTRANJIVACEAE","RAFFLESIACEAE","RANUNCULACEAE","RESTIONACEAE","RHACHIDOSORACEAE","RHAMNACEAE","RHIZOPHORACEAE","ROSACEAE","RUBIACEAE","RUPPIACEAE","RUTACEAE","SABIACEAE","SALICACEAE","SALVADORACEAE","SALVINIACEAE","SANTALACEAE","SAPINDACEAE","SAPOTACEAE","SAURURACEAE","SAXIFRAGACEAE","SCHISANDRACEAE","SCHIZAEACEAE","SCROPHULARIACEAE","SELAGINELLACEAE","SIMAROUBACEAE","SLADENIACEAE","SMILACACEAE","SOLANACEAE","SPHENOCLEACEAE","STAPHYLEACEAE","STEMONACEAE","STEMONURACEAE","STRELITZIACEAE","STYLIDIACEAE","STYRACACEAE","SYMPLOCACEAE","TALINACEAE","TAMARICACEAE","TAXODIACEAE","TECTARIACEAE","TEMONURACEAE","TETRAMELACEAE","THEACEAE","THELYPTERIDACEAE","THYMELAEACEAE","TORRICELLIACEAE","TRIURIDACEAE","TYPHACEAE","ULMACEAE","URTICACEAE","VERBENACEAE","VIOLACEAE","VISCACEAE","VITACEAE","XANTHORRHOEACEAE","XYRIDACEAE","ZAMIACEAE","ZINGIBERACEAE","ZYGOPHYLLACEAE"};
        for (String name :family_name) {
            ContentValues contentv = new ContentValues();
            contentv.put("name",name);
            db.insert("family_table", null, contentv);
        }
    }
}
